### ISSUE TITLE
Not running.. :/

### ISSUE THREAD

**Issue by EriikP4** [dhinakg/vm-rpc#7] opened 2020-07-25 17:06 UTC
It drop me an error:

![imagen](https://user-images.githubusercontent.com/50298335/88462204-e7161380-cea9-11ea-8e3d-a6cd06f5cf2b.png)

**Comment by dhinakg** [comment] 2020-09-09 04:09
@SrErikP, sorry, I didn't get notified for your issue for some reason.

Can you please run the following in `powershell`?

```powershell
Get-VM | Where { $_.State -eq 'Running' } | Select Name
```

Make sure to have the same VMs running as you had when you opened the issue.

**Comment by AcezukyRockon** [comment] 2021-04-18 06:34
Hi @dhinakg,

I got another error that maybe relate to the SrErikP's error:
![image](https://user-images.githubusercontent.com/36922874/115136424-e92c8d80-a049-11eb-84fd-4e78d8753ab4.png)

I also tried this command in Powershell (I think it run successfully since there are no error at all):
`Get-VM | Where { $_.State -eq 'Running' } | Select Name`
but the error in CMD is still there. 

Can I do something to fix it?
I'm using VMware workstation player 15.0) on Window 10 64 bit.

Thanks.

**Comment by dhinakg** [comment] 2021-04-18 19:49
It appears you pasted in a path with backslashes (the default on Windows), which is the escape character for JSON. Change them to forward slashes or double up the backslashes (so `\` to `\\`) so that it's properly escaped.

**Comment by AcezukyRockon** [comment] 2021-04-19 05:09
Thanks a lot! It worked :)
![image](https://user-images.githubusercontent.com/36922874/115184413-fd36c480-a107-11eb-814a-6358ceaf32ee.png)

**Comment by dhinakg** [comment] 2021-04-20 13:19
I'm gonna close this as there hasn't been any response. If someone can still reproduce this specific issue feel free to comment and I'll reopen it.

**Closed as completed by dhinakg** 2021-04-20 13:19 UTC

**Comment by LucasRosano** [comment] 2021-07-15 00:44
Well im getting this error and i tried the powershell command but it says that the term 'Get-VM' is not recognized as a name of a cmdlet.
